<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Linear Parameter Estimation – Bausteine Computergestützter Datenanalyse</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../skript/fehlerrechnung.html" rel="next">
<link href="../skript/normalverteilung.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-41d1ed59529443dc312b46011c211845.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<link rel="shortcut icon" href="skript/00-bilder/favicon_bcd_new.svg">
<link rel="icon" type="image/x-icon" href="logo.ico">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../skript/lineare-parameterschätzung.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Linear Parameter Estimation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../skript/00-bilder/logo_with_text_new.svg" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../skript/00-bilder/logo_with_text_new.svg" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Sensor Data Analysis Method Module</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sensor Data Analysis Method Module</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/einleitung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">The Principle of Measurements</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/normalverteilung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Normal Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/lineare-parameterschätzung.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Linear Parameter Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/fehlerrechnung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Error Calculation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/übung-hooke.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exercise: Hooke’s Law</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/kalibrierung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Calibration</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#measurement-series-hookes-law" id="toc-measurement-series-hookes-law" class="nav-link active" data-scroll-target="#measurement-series-hookes-law"><span class="header-section-number">3.1</span> Measurement Series: Hooke’s Law</a>
  <ul class="collapse">
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics">Descriptive Statistics</a></li>
  <li><a href="#exploratory-statistics" id="toc-exploratory-statistics" class="nav-link" data-scroll-target="#exploratory-statistics">Exploratory Statistics</a></li>
  </ul></li>
  <li><a href="#determining-the-spring-constant" id="toc-determining-the-spring-constant" class="nav-link" data-scroll-target="#determining-the-spring-constant"><span class="header-section-number">3.2</span> Determining the Spring Constant</a>
  <ul class="collapse">
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression">Linear Regression</a></li>
  <li><a href="#quantifying-measurement-deviation" id="toc-quantifying-measurement-deviation" class="nav-link" data-scroll-target="#quantifying-measurement-deviation">Quantifying Measurement Deviation</a></li>
  <li><a href="#the-scipy-module" id="toc-the-scipy-module" class="nav-link" data-scroll-target="#the-scipy-module">The SciPy Module</a></li>
  <li><a href="#spring-constant-result" id="toc-spring-constant-result" class="nav-link" data-scroll-target="#spring-constant-result">Spring Constant Result</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-hooke" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Linear Parameter Estimation</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Many physical quantities are measured indirectly. Frequently, there is a linear relationship between the measured quantity and the desired quantity. In practice, the data of a measurement series are never exact and are affected by more or less significant deviations from the true value of the desired quantity. Linear parameter estimation is a method used to determine, from a set of data, the value that minimizes the deviations of individual measured values.</p>
<p>Possible sources:</p>
<ul>
<li>https://messtechnik-und-sensorik.org/2-kennlinien-und-messgenauigkeit/<br>
</li>
<li>https://www.stssensors.com/de/characteristic-curve-hysteresis-measurement-error-terminology-in-pressure-measurement-technology/</li>
</ul>
<section id="measurement-series-hookes-law" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="measurement-series-hookes-law"><span class="header-section-number">3.1</span> Measurement Series: Hooke’s Law</h2>
<p><a href="https://en.wikipedia.org/wiki/Hooke%27s_law">Hooke’s law</a>, named after the English scientist Robert Hooke, describes the relationship between the force <span class="math inline">\(F\)</span> and the change in length <span class="math inline">\(\Delta x\)</span> of a spring by the equation<br>
<span class="math inline">\(F = k \cdot \Delta x\)</span>,<br>
where <span class="math inline">\(k\)</span> is the spring constant.</p>
<p>The spring constant is a fundamental property of elastic materials and indicates how much force is required to stretch or compress a spring by a certain length. Hooke’s law states that the deformation of an elastic body is proportional to the applied force, as long as the spring is not stretched or compressed beyond its elastic range.</p>
<p>In an experiment, Hooke’s law was tested. A metal spring hanging from a mount has a (variable) weight attached. Below it, at some distance, an ultrasonic sensor is placed for distance measurement. The distance between the underside of the weight attached to the spring and the ultrasonic sensor is the measured distance.</p>
<p>The weights were determined with an accuracy of <span class="math inline">\(\epsilon_{m} = 0.5\ \mathrm{g}\)</span> using a kitchen scale.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="00-bilder/aufbau.png" class="img-fluid figure-img" alt="Illustration of the experimental setup."></p>
<figcaption>Experimental Setup</figcaption>
</figure>
</div>
<p>The measurement series is provided as a CSV file located at the path <code>01-daten/hooke_data.csv</code>. The file is read using Pandas.</p>
<div id="1ee1a3b5" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>file_path <span class="op">=</span> <span class="st">"01-daten/hooke_data.csv"</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>hooke <span class="op">=</span> pd.read_csv(filepath_or_buffer<span class="op">=</span>file_path, sep<span class="op">=</span><span class="st">';'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h3>
<p>After loading the data, you should get an overview of it. With the methods <code>pd.DataFrame.head()</code> and <code>pd.DataFrame.tail()</code> you can view a snippet from the beginning and the end of the dataset.</p>
<div id="c5abd0aa" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(hooke.head(), <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(hooke.tail())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   no  mass  distance
0   0   705    153.29
1   1   705    152.74
2   2   705    153.27
3   3   705    152.81
4   4   705    152.77 

      no  mass  distance
109  109     0    173.70
110  110     0    173.44
111  111     0    173.75
112  112     0    173.30
113  113     0    200.00</code></pre>
</div>
</div>
<p>The method <code>pd.DataFrame.describe()</code> generates descriptive statistics for the dataset.<br>
In this case, however, the output is not particularly useful yet.<br>
The column ‘no’ contains only a running experiment number, and the column ‘mass’ contains different weights.</p>
<div id="10569204" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>hooke.describe()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">no</th>
<th data-quarto-table-cell-role="th">mass</th>
<th data-quarto-table-cell-role="th">distance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">count</th>
<td>114.000000</td>
<td>114.000000</td>
<td>114.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">mean</th>
<td>56.561404</td>
<td>394.921053</td>
<td>162.301754</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">std</th>
<td>33.131552</td>
<td>226.237605</td>
<td>7.483767</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">min</th>
<td>0.000000</td>
<td>0.000000</td>
<td>152.740000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">25%</th>
<td>28.250000</td>
<td>201.000000</td>
<td>156.622500</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">50%</th>
<td>56.500000</td>
<td>452.000000</td>
<td>160.720000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75%</th>
<td>84.750000</td>
<td>605.000000</td>
<td>167.767500</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">max</th>
<td>113.000000</td>
<td>705.000000</td>
<td>200.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>&nbsp;</p>
<p>It is more useful to have a descriptive statistic of the measured extension, grouped by the applied weight. For this, the Pandas method <code>pd.DataFrame.groupby()</code> can be used. This way, the arithmetic mean and standard deviation can be read for each of the measured weights.</p>
<div id="63448185" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>hooke.groupby(by<span class="op">=</span><span class="st">'mass'</span>)[<span class="st">'distance'</span>].describe()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">25%</th>
<th data-quarto-table-cell-role="th">50%</th>
<th data-quarto-table-cell-role="th">75%</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">mass</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>12.0</td>
<td>175.828333</td>
<td>7.620157</td>
<td>173.27</td>
<td>173.3150</td>
<td>173.570</td>
<td>174.1125</td>
<td>200.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">100</th>
<td>11.0</td>
<td>171.044545</td>
<td>0.985833</td>
<td>170.15</td>
<td>170.3650</td>
<td>170.800</td>
<td>171.2400</td>
<td>173.56</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">201</th>
<td>11.0</td>
<td>167.791818</td>
<td>0.296305</td>
<td>167.26</td>
<td>167.7200</td>
<td>167.780</td>
<td>167.9750</td>
<td>168.19</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">301</th>
<td>10.0</td>
<td>163.710000</td>
<td>1.660977</td>
<td>161.60</td>
<td>162.0575</td>
<td>163.825</td>
<td>165.3250</td>
<td>165.86</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">401</th>
<td>10.0</td>
<td>161.967000</td>
<td>0.313229</td>
<td>161.42</td>
<td>161.8450</td>
<td>161.915</td>
<td>162.0250</td>
<td>162.48</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">452</th>
<td>10.0</td>
<td>160.713000</td>
<td>0.627854</td>
<td>159.98</td>
<td>160.4575</td>
<td>160.555</td>
<td>160.7400</td>
<td>161.83</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">503</th>
<td>10.0</td>
<td>159.314000</td>
<td>0.781099</td>
<td>158.43</td>
<td>158.6400</td>
<td>159.220</td>
<td>159.9650</td>
<td>160.61</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">554</th>
<td>10.0</td>
<td>157.547000</td>
<td>0.523791</td>
<td>156.92</td>
<td>157.2075</td>
<td>157.435</td>
<td>157.7100</td>
<td>158.60</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">605</th>
<td>10.0</td>
<td>156.142000</td>
<td>0.354206</td>
<td>155.62</td>
<td>156.0700</td>
<td>156.080</td>
<td>156.2075</td>
<td>156.84</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">655</th>
<td>11.0</td>
<td>154.022727</td>
<td>0.224414</td>
<td>153.72</td>
<td>153.8800</td>
<td>153.920</td>
<td>154.2400</td>
<td>154.35</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">705</th>
<td>9.0</td>
<td>153.008889</td>
<td>0.241425</td>
<td>152.74</td>
<td>152.8100</td>
<td>152.910</td>
<td>153.2700</td>
<td>153.29</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>&nbsp;</p>
<p>Even at this point, the high standard deviation in the measurement series with 0 grams could be noticeable. It is, however, easier to spot when looking at the graphical representation.</p>
<div id="82a3239c" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>hooke.plot(x<span class="op">=</span><span class="st">'mass'</span>, y<span class="op">=</span><span class="st">'distance'</span>, kind<span class="op">=</span><span class="st">'scatter'</span>, title<span class="op">=</span><span class="st">"Hooke's Law Measurement Series"</span>, ylabel<span class="op">=</span><span class="st">'Distance in cm'</span>, xlabel<span class="op">=</span><span class="st">'Weight in grams'</span>, label<span class="op">=</span><span class="st">'Measured distance'</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lineare-parameterschätzung_files/figure-html/cell-7-output-1.png" alt="Plot of the weight on the x-axis and the measured distance on the y-axis." width="594" height="451" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>Graphically, the measurement of 200 cm for the weight 0 grams stands out as strongly deviating from the other measurements.</p>
<p>The measurements for the weight 0 grams will be examined more closely. For this purpose, the values are displayed both in absolute terms and <a href="https://en.wikipedia.org/wiki/Standard_score">standardized in units of the standard deviation (z-scores)</a>.</p>
<p>A variable is standardized by subtracting the mean from each value and dividing the result by the standard deviation.</p>
<p><span class="math display">\[
Z = \frac{x - \mu}{\sigma}
\]</span></p>
<p>Since the population mean and standard deviation are usually unknown, the sample mean and sample standard deviation are used instead. This procedure is called <em>studentization</em>, named after the pseudonym of William Sealy Gosset, who was mentioned in the previous chapter.</p>
<p><span class="math display">\[
z_{i} = \frac{x_{i} - \bar{x}}{s}
\]</span></p>
<div id="32fac05f" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>weight <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate z-transformation manually</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>mean_extension <span class="op">=</span> hooke[hooke[<span class="st">'mass'</span>] <span class="op">==</span> weight].loc[:, <span class="st">'distance'</span>].mean()</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>std_extension <span class="op">=</span> hooke[hooke[<span class="st">'mass'</span>] <span class="op">==</span> weight].loc[:, <span class="st">'distance'</span>].std(ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>z_values <span class="op">=</span> hooke[hooke[<span class="st">'mass'</span>] <span class="op">==</span> weight].loc[:, <span class="st">'distance'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: (x <span class="op">-</span> mean_extension) <span class="op">/</span> std_extension)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>z_values.name <span class="op">=</span> <span class="st">'z-values'</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># z-transformation using scipy</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co">## scipy returns a np.array</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="co">## for better display, convert the np.array to a pd.Series with a name attribute</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>scipy_z_values <span class="op">=</span> pd.Series(scipy.stats.zscore(hooke[hooke[<span class="st">'mass'</span>] <span class="op">==</span> weight].loc[:, <span class="st">'distance'</span>], ddof<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>scipy_z_values.name <span class="op">=</span> <span class="st">'scipy z-values'</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="co"># combined output of the data</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.concat([hooke[hooke[<span class="st">'mass'</span>] <span class="op">==</span> weight], z_values, scipy_z_values], axis<span class="op">=</span><span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        no  mass  distance  z-values  scipy z-values
102  102.0   0.0    173.32 -0.329171             NaN
103  103.0   0.0    174.11 -0.225498             NaN
104  104.0   0.0    173.42 -0.316048             NaN
105  105.0   0.0    174.12 -0.224186             NaN
106  106.0   0.0    173.30 -0.331795             NaN
107  107.0   0.0    174.21 -0.212375             NaN
108  108.0   0.0    173.27 -0.335732             NaN
109  109.0   0.0    173.70 -0.279303             NaN
110  110.0   0.0    173.44 -0.313423             NaN
111  111.0   0.0    173.75 -0.272742             NaN
112  112.0   0.0    173.30 -0.331795             NaN
113  113.0   0.0    200.00  3.172069             NaN
0      NaN   NaN       NaN       NaN       -0.329171
1      NaN   NaN       NaN       NaN       -0.225498
2      NaN   NaN       NaN       NaN       -0.316048
3      NaN   NaN       NaN       NaN       -0.224186
4      NaN   NaN       NaN       NaN       -0.331795
5      NaN   NaN       NaN       NaN       -0.212375
6      NaN   NaN       NaN       NaN       -0.335732
7      NaN   NaN       NaN       NaN       -0.279303
8      NaN   NaN       NaN       NaN       -0.313423
9      NaN   NaN       NaN       NaN       -0.272742
10     NaN   NaN       NaN       NaN       -0.331795
11     NaN   NaN       NaN       NaN        3.172069</code></pre>
</div>
</div>
<p>The value 200 cm in row 113 appears to be incorrect. A natural extension of the spring by an additional 16 centimeters is not plausible. The z-value &gt; 3 also marks the measurement as an <a href="https://en.wikipedia.org/wiki/Outlier">outlier</a>. Therefore, this row is removed from the dataset.</p>
<div id="imp-outlier" class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition&nbsp;3.1: Outlier
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>In statistics, a measurement is called an outlier if it deviates strongly from the rest of the data series. Multiple outliers can occur in a dataset. These values can be removed from the dataset to improve estimation if it is assumed that they are caused by measurement errors or other disturbances.</p>
<p>One way to identify outliers is the z-transformation. A threshold must be chosen, above which a measurement is classified as an outlier, e.g., 2.5 or 3 standard deviations. A variety of outlier tests have been developed in statistics (see <a href="https://en.wikipedia.org/wiki/Outlier#Outlier_tests">Outlier tests</a>).</p>
<p>However, classifying a measurement as an outlier cannot be based solely on statistical methods; it is always a judgment decision based on your domain knowledge. Not all extreme values are automatically invalid—they can occur with a certain statistical probability (see chapter on the Normal distribution). Such values are referred to as valid extreme values.</p>
<p>Outlier by various <a href="https://en.wikipedia.org/wiki/Outlier?uselang=en">authors</a> is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">CC BY-SA 4.0</a> and is available on <a href="https://en.wikipedia.org/wiki/Outlier">Wikipedia</a></p>
</div>
</div>
</div>
<div id="358b8e54" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>hooke.drop(index <span class="op">=</span> <span class="dv">113</span>, inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>hooke.groupby(by <span class="op">=</span> <span class="st">'mass'</span>)[<span class="st">'distance'</span>].describe()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">25%</th>
<th data-quarto-table-cell-role="th">50%</th>
<th data-quarto-table-cell-role="th">75%</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">mass</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>11.0</td>
<td>173.630909</td>
<td>0.367409</td>
<td>173.27</td>
<td>173.3100</td>
<td>173.440</td>
<td>173.9300</td>
<td>174.21</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">100</th>
<td>11.0</td>
<td>171.044545</td>
<td>0.985833</td>
<td>170.15</td>
<td>170.3650</td>
<td>170.800</td>
<td>171.2400</td>
<td>173.56</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">201</th>
<td>11.0</td>
<td>167.791818</td>
<td>0.296305</td>
<td>167.26</td>
<td>167.7200</td>
<td>167.780</td>
<td>167.9750</td>
<td>168.19</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">301</th>
<td>10.0</td>
<td>163.710000</td>
<td>1.660977</td>
<td>161.60</td>
<td>162.0575</td>
<td>163.825</td>
<td>165.3250</td>
<td>165.86</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">401</th>
<td>10.0</td>
<td>161.967000</td>
<td>0.313229</td>
<td>161.42</td>
<td>161.8450</td>
<td>161.915</td>
<td>162.0250</td>
<td>162.48</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">452</th>
<td>10.0</td>
<td>160.713000</td>
<td>0.627854</td>
<td>159.98</td>
<td>160.4575</td>
<td>160.555</td>
<td>160.7400</td>
<td>161.83</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">503</th>
<td>10.0</td>
<td>159.314000</td>
<td>0.781099</td>
<td>158.43</td>
<td>158.6400</td>
<td>159.220</td>
<td>159.9650</td>
<td>160.61</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">554</th>
<td>10.0</td>
<td>157.547000</td>
<td>0.523791</td>
<td>156.92</td>
<td>157.2075</td>
<td>157.435</td>
<td>157.7100</td>
<td>158.60</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">605</th>
<td>10.0</td>
<td>156.142000</td>
<td>0.354206</td>
<td>155.62</td>
<td>156.0700</td>
<td>156.080</td>
<td>156.2075</td>
<td>156.84</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">655</th>
<td>11.0</td>
<td>154.022727</td>
<td>0.224414</td>
<td>153.72</td>
<td>153.8800</td>
<td>153.920</td>
<td>154.2400</td>
<td>154.35</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">705</th>
<td>9.0</td>
<td>153.008889</td>
<td>0.241425</td>
<td>152.74</td>
<td>152.8100</td>
<td>152.910</td>
<td>153.2700</td>
<td>153.29</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>&nbsp;</p>
<p>The highest standard deviation is observed for the measurement series of 301 grams. However, the measured values appear unremarkable.</p>
<div id="0c73c752" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>weight <span class="op">=</span> <span class="dv">301</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co">## scipy returns a np.array</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">## for better display, the np.array is converted to a pd.Series, which has a name attribute</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>z_values <span class="op">=</span> pd.Series(scipy.stats.zscore(hooke[hooke[<span class="st">'mass'</span>] <span class="op">==</span> weight].loc[:, <span class="st">'distance'</span>], ddof<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>z_values.name <span class="op">=</span> <span class="st">'z-values'</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.concat([hooke[hooke[<span class="st">'mass'</span>] <span class="op">==</span> weight], z_values], axis<span class="op">=</span><span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      no   mass  distance  z-values
70  70.0  301.0    162.38       NaN
71  71.0  301.0    161.93       NaN
72  72.0  301.0    161.95       NaN
73  73.0  301.0    161.60       NaN
74  74.0  301.0    164.59       NaN
75  75.0  301.0    165.86       NaN
76  76.0  301.0    163.82       NaN
77  77.0  301.0    163.83       NaN
78  78.0  301.0    165.57       NaN
79  79.0  301.0    165.57       NaN
0    NaN    NaN       NaN -0.800734
1    NaN    NaN       NaN -1.071658
2    NaN    NaN       NaN -1.059617
3    NaN    NaN       NaN -1.270337
4    NaN    NaN       NaN  0.529809
5    NaN    NaN       NaN  1.294419
6    NaN    NaN       NaN  0.066226
7    NaN    NaN       NaN  0.072247
8    NaN    NaN       NaN  1.119823
9    NaN    NaN       NaN  1.119823</code></pre>
</div>
</div>
</section>
<section id="exploratory-statistics" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-statistics">Exploratory Statistics</h3>
<p>The plot of the cleaned dataset suggests a linear relationship. Additionally, the downward trend of the data points with increasing weight is striking.</p>
<div id="477a4eec" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>hooke.plot(x <span class="op">=</span> <span class="st">'mass'</span>, y <span class="op">=</span> <span class="st">'distance'</span>, kind <span class="op">=</span> <span class="st">'scatter'</span>, title <span class="op">=</span> <span class="st">'cleaned dataset'</span>, ylabel <span class="op">=</span> <span class="st">'Distance in cm'</span>, xlabel <span class="op">=</span> <span class="st">'Weight in grams'</span>, label <span class="op">=</span> <span class="st">'measured distance'</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lineare-parameterschätzung_files/figure-html/cell-11-output-1.png" alt="Representation of weight on the x-axis and measured distance on the y-axis." width="594" height="451" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>According to the experimental setup, as the spring is stretched, the distance to the distance sensor decreases. Since the spring elongation is to be measured, it is useful to transform the data accordingly. For this purpose, the measured distance at 0 grams of weight is taken as the zero point, from which the spring elongation is measured. This means that the arithmetic mean of the elongation measured at 0 grams is subtracted from all data points, and the result is multiplied by -1.</p>
<div id="5d05518d" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>zero_point <span class="op">=</span> hooke[hooke[<span class="st">'mass'</span>] <span class="op">==</span> <span class="dv">0</span>].loc[:, <span class="st">'distance'</span>].mean()</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Zero point: </span><span class="sc">{</span>zero_point<span class="sc">:.2f}</span><span class="ss"> cm"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>hooke[<span class="st">'distance'</span>] <span class="op">=</span> hooke[<span class="st">'distance'</span>].sub(zero_point).mul(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>hooke.plot(</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>x<span class="op">=</span><span class="st">'mass'</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>y<span class="op">=</span><span class="st">'distance'</span>,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>kind<span class="op">=</span><span class="st">'scatter'</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>title<span class="op">=</span><span class="st">'Corrected and Inverted Dataset'</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>ylabel<span class="op">=</span><span class="st">'Spring Extension in cm'</span>,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>xlabel<span class="op">=</span><span class="st">'Weight in grams'</span>,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>label<span class="op">=</span><span class="st">'Measured Distance'</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Zero point: 173.63 cm</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lineare-parameterschätzung_files/figure-html/cell-12-output-2.png" alt="Visualization of weight plotted on the x-axis and spring extension plotted on the y-axis." width="585" height="451" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>With the function <code>plt.errorbar()</code>, the means and standard errors for each weight can be displayed graphically. Since the standard errors are relatively small, horizontal lines are drawn at the ends of the error bars using the <code>capsize</code> parameter.</p>
<div id="afe11622" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean spring extension by weight</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>spring_means_by_weight <span class="op">=</span> hooke[<span class="st">'distance'</span>].groupby(by<span class="op">=</span>hooke[<span class="st">'mass'</span>]).mean()</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>spring_means_by_weight.name <span class="op">=</span> <span class="st">'Spring Extension'</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard error by weight</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>spring_stderr_by_weight <span class="op">=</span> hooke[<span class="st">'distance'</span>].groupby(by<span class="op">=</span>hooke[<span class="st">'mass'</span>]).std(ddof<span class="op">=</span><span class="dv">1</span>).div(np.sqrt(hooke[<span class="st">'distance'</span>].groupby(by<span class="op">=</span>hooke[<span class="st">'mass'</span>]).size()))</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>spring_stderr_by_weight.name <span class="op">=</span> <span class="st">'Standard Error'</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>data_points <span class="op">=</span> hooke.plot(</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>x<span class="op">=</span><span class="st">'mass'</span>, y<span class="op">=</span><span class="st">'distance'</span>, kind<span class="op">=</span><span class="st">'scatter'</span>,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>title<span class="op">=</span><span class="st">'cleaned and inverted dataset'</span>,</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>ylabel<span class="op">=</span><span class="st">'Spring Extension in cm'</span>, xlabel<span class="op">=</span><span class="st">'Weight in grams'</span>,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>alpha<span class="op">=</span><span class="fl">0.6</span>, label<span class="op">=</span><span class="st">'measured spring extension'</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Capture legend handles</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a><span class="co"># see: [https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.get_legend_handles_labels.html](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.get_legend_handles_labels.html)</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>data_points_handle, data_points_label <span class="op">=</span> data_points.get_legend_handles_labels()</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>errorbar_container <span class="op">=</span> plt.errorbar(</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>x<span class="op">=</span>spring_means_by_weight.index, y<span class="op">=</span>spring_means_by_weight, yerr<span class="op">=</span>spring_stderr_by_weight,</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>linestyle<span class="op">=</span><span class="st">'none'</span>, marker<span class="op">=</span><span class="st">'x'</span>, color<span class="op">=</span><span class="st">'black'</span>, markersize<span class="op">=</span><span class="dv">12</span>, elinewidth<span class="op">=</span><span class="dv">3</span>, ecolor<span class="op">=</span><span class="st">'red'</span>, capsize<span class="op">=</span><span class="dv">12</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Create legend manually</span></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a><span class="co"># see: [https://matplotlib.org/stable/api/container_api.html#matplotlib.container.ErrorbarContainer](https://matplotlib.org/stable/api/container_api.html#matplotlib.container.ErrorbarContainer)</span></span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>plt.legend(</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>[data_points_handle[<span class="dv">0</span>], errorbar_container.lines[<span class="dv">0</span>], errorbar_container.lines[<span class="dv">2</span>][<span class="dv">0</span>]],</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>[data_points_label[<span class="dv">0</span>], <span class="st">'Mean'</span>, <span class="st">'Standard Error'</span>],</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>loc<span class="op">=</span><span class="st">'upper left'</span></span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span>, pd.concat([spring_means_by_weight, spring_stderr_by_weight], axis<span class="op">=</span><span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lineare-parameterschätzung_files/figure-html/cell-13-output-1.png" alt="The x-axis shows the weight in grams, the y-axis shows the spring extension in cm. In addition to the measured points, the mean for each weight is plotted as a large X, with the range of the mean ± 1 standard error indicated from its center." width="585" height="451" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
       Spring Extension  Standard Error
mass                                  
0        -7.751375e-15        0.110778
100       2.586364e+00        0.297240
201       5.839091e+00        0.089339
301       9.920909e+00        0.525247
401       1.166391e+01        0.099052
452       1.291791e+01        0.198545
503       1.431691e+01        0.247005
554       1.608391e+01        0.165637
605       1.748891e+01        0.112010
655       1.960818e+01        0.067663
705       2.062202e+01        0.080475</code></pre>
</div>
</div>
</section>
</section>
<section id="determining-the-spring-constant" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="determining-the-spring-constant"><span class="header-section-number">3.2</span> Determining the Spring Constant</h2>
<p>The relationship between the force <span class="math inline">\(F\)</span> and the change in length <span class="math inline">\(\Delta{x}\)</span> of a spring with spring constant <span class="math inline">\(k\)</span> is described by the equation <span class="math inline">\(F = k \cdot \Delta{x}\)</span>. Here, the force <span class="math inline">\(F\)</span> corresponds to the weight in kilograms <span class="math inline">\(m\)</span> multiplied by the gravitational acceleration <span class="math inline">\(g\)</span>. On Earth, the gravitational acceleration is <span class="math inline">\(9.81 \frac{m}{s^2}\)</span>.</p>
<p>Therefore, in the dataset, the weight recorded in the ‘mass’ column (in grams) is converted to the actual force. Similarly, the measured displacement in the ‘distance’ column is converted from centimeters to meters.</p>
<div id="ff0afec6" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>hooke[<span class="st">'mass'</span>] <span class="op">=</span> hooke[<span class="st">'mass'</span>].div(<span class="dv">1000</span>).mul(<span class="fl">9.81</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>hooke.rename(columns <span class="op">=</span> {<span class="st">'mass'</span>: <span class="st">'force'</span>}, inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>hooke[<span class="st">'distance'</span>] <span class="op">=</span> hooke[<span class="st">'distance'</span>].div(<span class="dv">100</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(hooke.head())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   no    force  distance
0   0  6.91605  0.203409
1   1  6.91605  0.208909
2   2  6.91605  0.203609
3   3  6.91605  0.208209
4   4  6.91605  0.208609</code></pre>
</div>
</div>
<p>For the graphical representation of the relationship <span class="math inline">\(F = k \cdot \Delta{x}\)</span>, it is more practical to plot the displacement on the x-axis and the resulting force on the y-axis.</p>
<div id="6311b1f6" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>hooke.plot(x<span class="op">=</span><span class="st">'distance'</span>, y<span class="op">=</span><span class="st">'force'</span>, kind<span class="op">=</span><span class="st">'scatter'</span>, title<span class="op">=</span><span class="st">'Transformed Dataset'</span>, ylabel<span class="op">=</span><span class="st">'Resulting Force in $N$'</span>, xlabel<span class="op">=</span><span class="st">'Change in Distance in meters'</span>, label<span class="op">=</span><span class="st">'Measured Change in Distance'</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lineare-parameterschätzung_files/figure-html/cell-15-output-1.png" alt="Plot of spring extension on the x-axis and resulting force on the y-axis." width="577" height="451" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression">Linear Regression</h3>
<p>Linear regression (or parameter estimation) is a method used to estimate the unknown parameters of the underlying physical model for a set of measurements. The goal is to determine a (in this case linear) function that best fits the observed data. (<a href="https://en.wikipedia.org/wiki/Linear_regression">Wikipedia</a>)</p>
<p>A linear function is determined by the constant <span class="math inline">\(\beta_0\)</span>, the y-intercept, and the slope coefficient <span class="math inline">\(\beta_1\)</span>.</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 \cdot x
\]</span></p>
<p>Typically, there is no deterministic relationship; instead, random deviations occur, which are expressed using the additive error term, denoted in English as <span class="math inline">\(e_i\)</span>. These errors are called residuals.</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 \cdot x + e_i
\]</span></p>
<p>To determine the parameters of a linear function, the method of <a href="https://en.wikipedia.org/wiki/Least_squares">least squares</a> is used.</p>
<div id="nte-ols" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example&nbsp;3.2: Least Squares Method
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The least squares method aims to find the line <span class="math inline">\(\hat{y} = \beta_0 + \beta_1 \cdot x\)</span> that minimizes the squared distances between the predicted values <span class="math inline">\(\hat{y}\)</span> and the actual measured values <span class="math inline">\(y\)</span>. The values <span class="math inline">\(y_i - \hat{y_i}\)</span> are the residuals <span class="math inline">\(e_i\)</span>. Therefore, it holds that:</p>
<p><span class="math display">\[
\sum_{i=1}^{N}(y_i - \hat{y_i})^2 = \sum_{i=1}^{N} e_i^2 = \min
\]</span></p>
<p>Graphically, the minimization of the squared distances can be visualized as follows.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Code</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div id="8bfdc100" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lineare-parameterschätzung_files/figure-html/cell-16-output-1.png" alt="On a line, 9 points are marked representing the predicted values of the linear model. Above or below each, the measured values are shown. Each predicted value is connected to a measured value with a dashed vertical line." width="569" height="411" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Regression coefficients: [ 2.93333333 -0.73333333]</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div id="7e4151d6" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.arange(<span class="dv">1</span>, <span class="dv">11</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> <span class="op">-</span> x.copy() <span class="op">+</span> <span class="dv">4</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>y[<span class="dv">0</span>] <span class="op">-=</span> <span class="dv">2</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>y[<span class="dv">2</span>] <span class="op">-=</span> <span class="dv">2</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>y[<span class="dv">3</span>] <span class="op">+=</span> <span class="dv">3</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>y[<span class="op">-</span><span class="dv">3</span>] <span class="op">+=</span> <span class="dv">5</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>lm <span class="op">=</span> poly.polyfit(x, y, <span class="dv">1</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>predicted_values <span class="op">=</span> poly.polyval(x, lm)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>plt.scatter(x, predicted_values, label<span class="op">=</span><span class="st">'Predicted values'</span>, marker<span class="op">=</span><span class="st">"^"</span>, color<span class="op">=</span><span class="st">"tab:blue"</span>)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>plt.scatter(x, y, label<span class="op">=</span><span class="st">'Measured values'</span>, marker<span class="op">=</span><span class="st">'o'</span>, color<span class="op">=</span><span class="st">"tab:orange"</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>plt.axline(xy1<span class="op">=</span>(<span class="dv">0</span>, lm[<span class="dv">0</span>]), slope<span class="op">=</span>lm[<span class="dv">1</span>], label<span class="op">=</span><span class="st">"Regression line"</span>, color<span class="op">=</span><span class="st">"tab:blue"</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>dotted <span class="op">=</span> plt.vlines(x, ymin<span class="op">=</span>predicted_values, ymax<span class="op">=</span>y, alpha<span class="op">=</span><span class="fl">0.6</span>, ls<span class="op">=</span><span class="st">'dotted'</span>, label<span class="op">=</span><span class="st">'Residuals'</span>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Regression coefficients:"</span>, lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>The drawn line corresponds to the linear function <span class="math inline">\(\hat{y} = \beta_0 + \beta_1 \cdot x + e_i\)</span>. The triangle markers are the predicted values <span class="math inline">\(\hat{y_i}\)</span> of the linear model for the values <span class="math inline">\(x_i = np.arange(1, 11)\)</span>. The actual measurements <span class="math inline">\(y\)</span> are marked with circle markers. The length of the dashed lines represents the magnitude of the deviation between the observed and predicted values <span class="math inline">\(y_i - \hat{y_i}\)</span>, i.e., the residuals <span class="math inline">\(e_i\)</span>.</p>
<p>We are looking for the line that minimizes the sum of squared residuals. The values <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> we are seeking are the least squares estimators.</p>
<p><span class="math display">\[
\beta_0 = \bar{y} - \beta_1 \cdot \bar{x}
\]</span></p>
<p><span class="math display">\[
\beta_1 = { \sum_{i=1}^n (x_i- \bar{x}) \cdot (y_i - \bar{y}) \over \sum_{i=1}^n (x_i - \bar{x})^2 }
\]</span></p>
<p>For completeness, we will derive the least squares estimators. We are searching for values of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> that minimize the sum of squared residuals <span class="math inline">\(\sum_{i=1}^{n} e_i^2\)</span>. The sum of squared residuals is the sum of the squared differences between the observed values <span class="math inline">\(y_i\)</span> and the values predicted by the linear function. <span class="math display">\[
\sum_{i=1}^{n} e_i^2 ~ = ~ \sum_{i=1}^{n} (y_i - (\beta_0 + \beta_1 \cdot x_i))^2
\]</span></p>
<p>We are thus examining a function that depends on two variables. <span class="math display">\[
f(\beta_0, \beta_1) = \sum_{i=1}^{n} (y_i - (\beta_0 + \beta_1 \cdot x_i))^2
\]</span></p>
<p>The summation symbol is shorthand for a sum. <span class="math display">\[
f(\beta_0, \beta_1) = (y_1 - (\beta_0 + \beta_1 \cdot x_1))^2 ~ + ~ (y_2 - (\beta_0 + \beta_1 \cdot x_2))^2 ~ + ~ ... ~ (y_n - (\beta_0 + \beta_1 \cdot x_n))^2
\]</span></p>
<p>At the minimum of the function, both partial derivatives must be zero (an easy explanation is <a href="https://www.sofatutor.com/mathematics/functions/multivariable-functions/local-extrema-of-multivariable-functions">here</a>).</p>
<div id="nte-partialderivative" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example&nbsp;3.1: Partial Derivative
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A partial derivative is the derivative of a function with multiple variables with respect to one variable, treating the other variables as constants.</p>
<p>For a function <span class="math inline">\(f(x, y) = 2x + y^2\)</span>, the partial derivative with respect to <span class="math inline">\(x\)</span> is expressed as:</p>
<p><span class="math inline">\(\frac{\partial f(x, y)}{\partial x}\)</span></p>
<ul>
<li>The symbol ∂ is the cursive form of the Cyrillic lowercase letter д (d) and is read as “del”. It indicates a partial derivative is being taken.</li>
<li>The numerator contains the function to be differentiated. The denominator shows the variable with respect to which differentiation is performed. The term is read as “del f of x and y with respect to del x”.</li>
</ul>
<p>The partial derivative <span class="math inline">\(\frac{\partial f(x, y)}{\partial x} = 2\)</span>. <span class="math inline">\(y^2\)</span> is treated as a constant (e.g., <span class="math inline">\(5^2\)</span>) and thus its derivative is zero.</p>
<p>The partial derivative <span class="math inline">\(\frac{\partial f(x, y)}{\partial y} = 2y\)</span>. <span class="math inline">\(2x\)</span> is treated as a constant and its derivative is zero.</p>
</div>
</div>
</div>
<p>In both partial derivatives, <span class="math inline">\(x_i\)</span> and <span class="math inline">\(y_i\)</span> are constants. In the partial derivative with respect to <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span> is also constant; in the partial derivative with respect to <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_0\)</span> is constant.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Partial derivative with respect to the intercept</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Partial derivative with respect to the slope</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p>For the partial derivative with respect to <span class="math inline">\(\beta_0\)</span>, applying the chain rule for the outer function (top) and inner function (middle) gives: <span class="math display">\[ \begin{aligned}
\frac{\partial f(\beta_0, \beta_1)}{\partial \beta_0} = 2 \cdot (y_1 - (\beta_0 + \beta_1 \cdot x_1)) ~ + ~ ... ~ (y_n - (\beta_0 + \beta_1 \cdot x_n)) = 2 \cdot \sum_{i=1}^{n} (y_i - (\beta_0 + \beta_1 \cdot x_i)) ~ \cdot
\newline
(0 - (1 + 0 \cdot 0)) ~ + ~ ... ~ (0 - (1 + 0 \cdot 0)) = \sum_{i=1}^{n} (0 - (1 + 0 \cdot 0)) =
\newline
2 \cdot \sum_{i=1}^{n} (y_i - (\beta_0 + \beta_1 \cdot x_i)) ~ \cdot (-1)
\end{aligned}
\]</span></p>
<p>Thus, the partial derivative with respect to <span class="math inline">\(\beta_0\)</span> is: <span class="math display">\[
\frac{\partial f(\beta_0, \beta_1)}{\partial \beta_0} = -2 \cdot \sum_{i=1}^{n} (y_i - (\beta_0 + \beta_1 \cdot x_i)) = 0
\]</span></p>
<p>This can be simplified by dropping the factor <span class="math inline">\(-2\)</span> (since <span class="math inline">\(-2 \cdot 0 = 0\)</span>) and resolving the signs. Thus: <span class="math display">\[
\sum_{i=1}^{n} (y_i - \beta_0 - \beta_1 \cdot x_i) = 0
\]</span></p>
<p>Or equivalently: <span class="math display">\[
\sum_{i=1}^{n} y_i - \sum_{i=1}^{n} \beta_0 - \sum_{i=1}^{n} \beta_1 \cdot x_i = 0
\]</span></p>
<p><span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are constants, so <span class="math inline">\(\sum_{i=1}^{n} \beta_0  = \beta_0 \cdot \sum_{i=1}^{n} 1 = \beta_0 \cdot n\)</span> and <span class="math inline">\(\sum_{i=1}^{n} \beta_1 \cdot x_i = \beta_1 \cdot \sum_{i=1}^{n} 1 \cdot x_i\)</span>. Hence: <span class="math display">\[
\sum_{i=1}^{n} y_i - n \cdot \beta_0 - \beta_1 \cdot \sum_{i=1}^{n} x_i = 0
\]</span></p>
<p>Now we can divide by <span class="math inline">\(n\)</span>. Here, <span class="math inline">\(\frac{\sum_{i=1}^{n} y_i}{n}\)</span> corresponds to the arithmetic mean of <span class="math inline">\(y\)</span>, and <span class="math inline">\(\frac{\sum_{i=1}^{n} x_i}{n}\)</span> to the arithmetic mean of <span class="math inline">\(x\)</span>. Thus, we obtain: <span class="math display">\[
\bar{y} - \beta_0 - \beta_1 \cdot \bar{x}= 0
\]</span></p>
<p>Rearranged: <span class="math display">\[
\beta_0 = \bar{y} - \beta_1 \cdot \bar{x}
\]</span></p>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p>For the partial derivative with respect to <span class="math inline">\(\beta_1\)</span>, the chain rule is applied similarly: <span class="math display">\[ \begin{aligned}
\frac{\partial f(\beta_0, \beta_1)}{\partial \beta_1} = 2 \cdot (y_1 - (\beta_0 + \beta_1 \cdot x_1)) ~ + ~ ... ~ (y_n - (\beta_0 + \beta_1 \cdot x_n)) = 2 \cdot \sum_{i=1}^{n} (y_i - (\beta_0 + \beta_1 \cdot x_i)) ~ \cdot
\newline
(0 - (0 + 1 \cdot x_1)) ~ + ~ ... ~ (0 - (0 + 1 \cdot x_n)) ~ = ~ \sum_{i=1}^{n} -x_i =
\newline
2 \cdot \sum_{i=1}^{n} (y_i - (\beta_0 + \beta_1 \cdot x_i)) ~ \cdot -x_i
\end{aligned}
\]</span></p>
<p>Thus: <span class="math display">\[
\frac{\partial f(\beta_0, \beta_1)}{\partial \beta_1} = -2 \sum_{i=1}^{n} x_i \cdot (y_i - (\beta_0 + \beta_1 \cdot x_i)) = 0
\]</span></p>
<p>Dropping the factor <span class="math inline">\(-2\)</span> and expanding gives: <span class="math display">\[
\sum_{i=1}^{n} x_iy_i - \sum_{i=1}^{n}  \beta_0 \cdot x_i - \sum_{i=1}^{n}  \beta_1 \cdot x_i^2 = 0
\]</span></p>
<p>Factoring constants: <span class="math display">\[
\sum_{i=1}^{n} x_iy_i - \beta_0 \cdot \sum_{i=1}^{n} x_i - \beta_1 \cdot \sum_{i=1}^{n} x_i^2 = 0
\]</span></p>
<p>Substitute <span class="math inline">\(\beta_0 = \bar{y} - \beta_1 \cdot \bar{x}\)</span> and <span class="math inline">\(\sum_{i=1}^{n} x_i = n \cdot \bar{x}\)</span>: <span class="math display">\[
\sum_{i=1}^{n} x_iy_i - (\bar{y} - \beta_1 \cdot \bar{x}) \cdot  n \cdot \bar{x} - \beta_1 \cdot \sum_{i=1}^{n} x_i^2 = 0
\]</span></p>
<p>Expanding: <span class="math display">\[
\sum_{i=1}^{n} x_iy_i - n\bar{x}\bar{y} - \beta_1 \cdot n\bar{x}^2 - \beta_1 \cdot \sum_{i=1}^{n} x_i^2 = 0
\]</span></p>
<p>Combine the last two terms: <span class="math display">\[
\sum_{i=1}^{n} x_iy_i - n\bar{x}\bar{y} - \beta_1 \cdot ( \sum_{i=1}^{n} x_i^2 - n \bar{x}^2) = 0
\]</span></p>
<p>Solve for <span class="math inline">\(\beta_1\)</span>: <span class="math display">\[
\beta_1 \cdot \left( \sum_{i=1}^{n} x_i^2 - n \bar{x}^2 \right) = \sum_{i=1}^{n} x_i y_i - n \bar{x} \bar{y}
\]</span></p>
<p>Then: <span class="math display">\[
\beta_1 = \frac{\sum_{i=1}^{n} x_i y_i - n \bar{x} \bar{y}}{\sum_{i=1}^{n} x_i^2 - n \bar{x}^2}
\]</span></p>
<p>Now, we can first rewrite using <span class="math inline">\(\sum_{i=1}^{n} x_i^2 - n \bar{x}^2 = \sum_{i=1}^{n} (x_i - \bar{x})^2\)</span>. <span class="math display">\[
\beta_1 = \frac{\sum_{i=1}^{n} x_i y_i - n \bar{x} \bar{y}}{\sum_{i=1}^{n} (x_i - \bar{x})^2}
\]</span></p>
<p>Then—and this will be shown next—using <span class="math inline">\(\sum_{i=1}^{n} x_i y_i - n \bar{x} \bar{y} = \sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})\)</span>. Thus, we obtain: <span class="math display">\[
\beta_1 = \frac{\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n} (x_i - \bar{x})^2}
\]</span></p>
<p>The final step is shown starting from the result and begins by expanding the product: <span class="math display">\[
\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y}) = \sum_{i=1}^{n} (x_i y_i - x_i \bar{y} - \bar{x} y_i + \bar{x} \bar{y})
\]</span></p>
<p>This can also be written as: <span class="math display">\[
\sum_{i=1}^{n} x_i y_i - \sum_{i=1}^{n} x_i \bar{y} - \sum_{i=1}^{n} \bar{x} y_i + \sum_{i=1}^{n} \bar{x} \bar{y}
\]</span></p>
<p><span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(\bar{y}\)</span> are constants, so we can write <span class="math inline">\(\bar{x} \cdot \sum_{i=1}^{n} y_i\)</span> and <span class="math inline">\(\bar{y} \cdot \sum_{i=1}^{n} x_i\)</span>. Since <span class="math inline">\(\sum_{i=1}^{n} x_i = n \cdot \bar{x}\)</span> (analogously for <span class="math inline">\(y\)</span>), we obtain: <span class="math display">\[
\sum_{i=1}^{n} x_i y_i - \bar{y} \cdot n \cdot \bar{x} - \bar{x} \cdot n \cdot \bar{y} + \sum_{i=1}^{n} \bar{x} \bar{y}
\]</span></p>
<p>Reordering: <span class="math display">\[
\sum_{i=1}^{n} x_i y_i - n \bar{x} \bar{y} - n \bar{x} \bar{y} + \sum_{i=1}^{n} \bar{x} \bar{y}
\]</span></p>
<p>The last term <span class="math inline">\(\sum_{i=1}^{n} \bar{x} \bar{y}\)</span> can also be written as <span class="math inline">\(n \cdot \bar{x} \bar{y}\)</span>, which yields: <span class="math display">\[
\sum_{i=1}^{n} x_i y_i - n \bar{x} \bar{y} - n \bar{x} \bar{y} + n \bar{x} \bar{y}
\]</span></p>
<p>The last two terms therefore cancel out, leaving: <span class="math display">\[
\sum_{i=1}^{n} x_i y_i - n \bar{x} \bar{y}
\]</span></p>
<p><span class="citation" data-cites="Baitsch-2019">(<a href="#ref-Baitsch-2019" role="doc-biblioref">Baitsch, Matthias 2019, 73–74</a>)</span></p>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The functions required for this are provided both by the <code>numpy.polynomial</code> package—specifically its <code>numpy.polynomial.polynomial</code> module for polynomial functions—and by the <code>scipy.stats.linregress</code> module. In the following, the computation using NumPy is demonstrated first, followed by an introduction to the functions from the SciPy module. The way both modules work is similar.</p>
<section id="numpy-polyfit-and-polyeval" class="level4">
<h4 class="anchored" data-anchor-id="numpy-polyfit-and-polyeval">NumPy polyfit and polyeval</h4>
<div id="c2be968e" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy.polynomial.polynomial <span class="im">as</span> poly</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>To estimate function parameters using the least squares method, the function <code>poly.polyfit(x, y, deg)</code> is used. <code>x</code> represents the values of the independent variable, <code>y</code> the values of the dependent variable, and <code>deg</code> specifies the degree of the polynomial function to be fitted. <code>deg = 1</code> specifies a linear function.</p>
<div id="nte-polyfitpolyeval" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example&nbsp;3.3: Explaining polyfit and polyeval
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="60f1efc9" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate example data</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.array(<span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">100</span>)))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> x <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(poly.polyfit(x, y, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[-1617.    99.]</code></pre>
</div>
</div>
<p>The function returns the estimated regression parameters as a NumPy array. The terms are arranged in ascending order, i.e., the intercept is at index position 0, and the slope coefficient is at index position 1. The output for a second-degree polynomial, for example, would look like this:</p>
<div id="b9a8dd73" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(poly.polyfit(x, y, <span class="dv">2</span>).<span class="bu">round</span>(<span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[-0.  0.  1.]</code></pre>
</div>
</div>
<p>With the regression coefficients, the predicted values of the linear function can be computed. For this, the function <code>poly.polyeval(x, c)</code> is used. It calculates the function values for the values passed in <code>x</code> using the function parameters <code>c</code>. From the difference between the measured values and the predicted values, the residuals can be determined.</p>
<div id="88a471eb" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 'manual' calculation</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>regressions_koeffizienten <span class="op">=</span> poly.polyfit(x, y, <span class="dv">1</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>vorhersagewerte <span class="op">=</span> regressions_koeffizienten[<span class="dv">0</span>] <span class="op">+</span> x <span class="op">*</span> regressions_koeffizienten[<span class="dv">1</span>]</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>residuen <span class="op">=</span> y <span class="op">-</span> vorhersagewerte</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co"># calculation with polyeval</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>lm <span class="op">=</span> poly.polyfit(x, y, <span class="dv">1</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>vorhersagewerte_polyval <span class="op">=</span> poly.polyval(x, lm)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The results match:"</span>, np.equal(vorhersagewerte, vorhersagewerte_polyval).<span class="bu">all</span>())</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Excerpt of predicted values:"</span>, vorhersagewerte[:<span class="dv">10</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>The results match: True

Excerpt of predicted values: [-1617. -1518. -1419. -1320. -1221. -1122. -1023.  -924.  -825.  -726.]</code></pre>
</div>
</div>
<p>The <a href="https://en.wikipedia.org/wiki/Coefficient_of_determination">coefficient of determination</a> <span class="math inline">\(R^2\)</span> indicates how well the estimated function fits the data. Its range goes from 0 to 1. A value of 1 represents a perfect fit. For a simple linear regression with only one explanatory variable, the coefficient of determination can be calculated as the square of the <a href="https://en.wikipedia.org/wiki/Pearson_correlation_coefficient">Bravais–Pearson correlation coefficient</a> <span class="math inline">\(r\)</span>. It can be obtained using the function <code>np.corrcoef(x, y)</code> (which returns a matrix of correlation coefficients).</p>
<div id="81f06d62" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"r = </span><span class="sc">{</span>np<span class="sc">.</span>corrcoef(x, y)[<span class="dv">0</span>, <span class="dv">1</span>]<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R</span><span class="ch">\u00b2</span><span class="ss"> = </span><span class="sc">{</span>np<span class="sc">.</span>corrcoef(x, y)[<span class="dv">0</span>, <span class="dv">1</span>] <span class="op">**</span> <span class="dv">2</span><span class="sc">:.2f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>r = 0.97
R² = 0.94</code></pre>
</div>
</div>
<p>The data and the estimated line can be displayed graphically.</p>
<div id="227dd4cd" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>plt.scatter(x, y, label<span class="op">=</span><span class="st">'Sample data'</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>plt.plot(x, vorhersagewerte, label<span class="op">=</span><span class="st">'Predicted values'</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>plt.annotate(<span class="st">"$R^2$ = </span><span class="sc">{:.2f}</span><span class="st">"</span>.<span class="bu">format</span>(np.corrcoef(x, y)[<span class="dv">0</span>, <span class="dv">1</span>] <span class="op">**</span> <span class="dv">2</span>), (<span class="bu">max</span>(x) <span class="op">*</span> <span class="fl">0.9</span>, <span class="dv">1</span>))</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>plt.title(label<span class="op">=</span><span class="st">'Sample Data and Estimated Linear Function'</span>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'x-values'</span>)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'y-values'</span>)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lineare-parameterschätzung_files/figure-html/cell-23-output-1.png" width="614" height="451" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>NumPy also includes the now outdated functions <code>np.polyfit(x, y, deg)</code> and <code>np.polyval(p, x)</code>.</p>
<div id="nte-polyfit" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example&nbsp;3.4: np.polyfit &amp; np.polyval
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The functions <code>np.polyfit(x, y, deg)</code> and <code>np.polyval(p, x)</code> work similarly to the functions introduced from the <code>numpy.polynomial.polynomial</code> module. However, an important difference is that <strong>the parameters returned by <code>polyfit</code> are in reverse order</strong>.</p>
<div id="31e854fb" class="cell" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(poly.polyfit(x, y, deg <span class="op">=</span> <span class="dv">1</span>))</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.polyfit(x, y, deg <span class="op">=</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[-1617.    99.]
[   99. -1617.]</code></pre>
</div>
</div>
<div class="border">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This forms part of the old polynomial API. Since version 1.4, the new polynomial API defined in <code>numpy.polynomial</code> is preferred. A summary of the differences can be found in the <a href="https://numpy.org/doc/stable/reference/routines.polynomials.html">transition guide</a>.</p>
</div>
</div>
<p><a href="https://numpy.org/doc/stable/reference/generated/numpy.polyfit.html">NumPy Documentation</a></p>
</div>
</div>
</div>
</div>
<p>The parameters of the linear function fitted to the measured values and the coefficient of determination are:</p>
<div id="15748c7c" class="cell" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(poly.polyfit(hooke[<span class="st">'distance'</span>], hooke[<span class="st">'force'</span>], <span class="dv">1</span>))</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"r = </span><span class="sc">{</span>np<span class="sc">.</span>corrcoef(hooke[<span class="st">'distance'</span>], hooke[<span class="st">'force'</span>])[<span class="dv">0</span>, <span class="dv">1</span>]<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R</span><span class="ch">\u00b2</span><span class="ss"> = </span><span class="sc">{</span>np<span class="sc">.</span>corrcoef(hooke[<span class="st">'distance'</span>], hooke[<span class="st">'force'</span>])[<span class="dv">0</span>, <span class="dv">1</span>] <span class="op">**</span> <span class="dv">2</span><span class="sc">:.2f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[ 0.05753159 33.01899551]
r = 0.99
R² = 0.99</code></pre>
</div>
</div>
<p>With the regression coefficients, the predicted values of the linear function can be calculated.</p>
<div id="4f985bad" class="cell" data-execution_count="25">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculation with polyeval</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>lm <span class="op">=</span> poly.polyfit(hooke[<span class="st">'distance'</span>], hooke[<span class="st">'force'</span>], <span class="dv">1</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>predicted_values_hooke <span class="op">=</span> poly.polyval(hooke[<span class="st">'distance'</span>], lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The measurement series and the linear function fitted to it can be displayed graphically.</p>
<div id="4e32c7c7" class="cell" data-execution_count="26">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Placeholder x &amp; y</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> hooke[<span class="st">'distance'</span>]</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> hooke[<span class="st">'force'</span>]</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create plot</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>plt.scatter(x, y, label<span class="op">=</span><span class="st">'Measured data'</span>)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>plt.axline(xy1<span class="op">=</span>(<span class="dv">0</span>, lm[<span class="dv">0</span>]), slope<span class="op">=</span>lm[<span class="dv">1</span>], label<span class="op">=</span><span class="st">'Regression line</span><span class="ch">\n</span><span class="st">y = '</span> <span class="op">+</span> <span class="st">"</span><span class="sc">{beta_0:.3f}</span><span class="st">"</span>.<span class="bu">format</span>(beta_0<span class="op">=</span>lm[<span class="dv">0</span>]) <span class="op">+</span> <span class="st">' + '</span> <span class="op">+</span> <span class="st">"</span><span class="sc">{beta_1:.3f}</span><span class="st"> "</span>.<span class="bu">format</span>(beta_1<span class="op">=</span>lm[<span class="dv">1</span>]) <span class="op">+</span> <span class="st">'x'</span>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>plt.annotate(<span class="st">"$R^2$ = </span><span class="sc">{:.2f}</span><span class="st">"</span>.<span class="bu">format</span>(np.corrcoef(x, y)[<span class="dv">0</span>, <span class="dv">1</span>] <span class="op">**</span> <span class="dv">2</span>), (<span class="bu">max</span>(x) <span class="op">*</span> <span class="fl">0.9</span>, <span class="dv">1</span>))</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Measured data and estimated linear function'</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Measured change in displacement (m)'</span>)</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Applied force'</span>)</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lineare-parameterschätzung_files/figure-html/cell-27-output-1.png" alt="Experimental spring data (change in displacement vs. applied force) with regression line." width="577" height="451" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="quantifying-measurement-deviation" class="level3">
<h3 class="anchored" data-anchor-id="quantifying-measurement-deviation">Quantifying Measurement Deviation</h3>
<p>For the estimated regression coefficient, the standard error of the regression coefficient <span class="math inline">\(SE = \hat{\sigma}_{\hat{\beta_1}}\)</span> can be calculated for simple linear regression with one explanatory variable (see <a href="https://en.wikipedia.org/wiki/Standard_error_(statistics)#Regression_coefficients">Wikipedia</a>).</p>
<p><span class="math display">\[
SE = \sqrt{\frac{\frac{1}{n-2} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2}{ \sum_{i=1}^{n} (x_i - \bar{x})^2}}
\]</span></p>
<ul>
<li>The numerator contains the mean <a href="https://en.wikipedia.org/wiki/Residual_sum_of_squares">residual sum of squares</a> (sum of squared residuals / degrees of freedom).</li>
<li>The denominator contains the <a href="https://en.wikipedia.org/wiki/Sum_of_squares#Deviation_from_the_mean">sum of squares of deviations of <span class="math inline">\(x\)</span></a>.</li>
</ul>
<p>For a significance level <span class="math inline">\(\alpha\)</span>, a confidence level <span class="math inline">\(1 - \alpha\)</span> can be given as:</p>
<p><span class="math display">\[
\hat{\beta_1} \pm SE \cdot t_{1-\alpha / 2} ~ (n - 2)
\]</span></p>
<ul>
<li><span class="math inline">\(t_{1-\alpha / 2} ~ (n - 2)\)</span> is the value from the t-distribution with n - 2 degrees of freedom, or equivalently the return value of the function:
<ul>
<li><code>scipy.stats.t.ppf(q = 1 - alpha/2, df = n - 2)</code> for the upper bound of the interval.</li>
</ul></li>
</ul>
<div id="18ba6cf6" class="cell" data-execution_count="27">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Regression coefficient: </span><span class="sc">{</span>lm[<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the standard error of the regression coefficient 'manually'</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>standard_error_beta_1 <span class="op">=</span> np.sqrt( (<span class="dv">1</span> <span class="op">/</span> (<span class="bu">len</span>(x) <span class="op">-</span> <span class="dv">2</span>) <span class="op">*</span> <span class="bu">sum</span>((y <span class="op">-</span> predicted_values_hooke) <span class="op">**</span> <span class="dv">2</span>)) <span class="op">/</span> <span class="bu">sum</span>( (x <span class="op">-</span> x.mean()) <span class="op">**</span> <span class="dv">2</span>  ))</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Standard error of the regression coefficient: </span><span class="sc">{</span>standard_error_beta_1<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose significance level (alpha level) 1 - 95%</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(x)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>t_value <span class="op">=</span> scipy.stats.t.ppf(q <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> alpha<span class="op">/</span><span class="dv">2</span>, df <span class="op">=</span> n <span class="op">-</span> <span class="dv">2</span>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"t-value 95% interval (two-sided): </span><span class="sc">{</span>t_value<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95% confidence interval: </span><span class="sc">{</span>lm[<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss"> ± </span><span class="sc">{</span>t_value<span class="sc">:.4f}</span><span class="ss"> * </span><span class="sc">{</span>standard_error_beta_1<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"lower 95% interval bound: </span><span class="sc">{</span>lm[<span class="dv">1</span>] <span class="op">-</span> t_value <span class="op">*</span> standard_error_beta_1<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"upper 95% interval bound: </span><span class="sc">{</span>lm[<span class="dv">1</span>] <span class="op">+</span> t_value <span class="op">*</span> standard_error_beta_1<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Regression coefficient: 33.0190
Standard error of the regression coefficient: 0.3784
t-value 95% interval (two-sided): 1.9816
95% confidence interval: 33.0190 ± 1.9816 * 0.3784
lower 95% interval bound: 32.2692
upper 95% interval bound: 33.7688</code></pre>
</div>
</div>
<p>The confidence interval can also be represented graphically.</p>
<div id="d79376df" class="cell" data-execution_count="28">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Placeholder x &amp; y</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> hooke[<span class="st">'distance'</span>]</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> hooke[<span class="st">'force'</span>]</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create plot</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>plt.scatter(x, y, label<span class="op">=</span><span class="st">'Measured data'</span>)</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>plt.axline(xy1<span class="op">=</span>(<span class="dv">0</span>, lm[<span class="dv">0</span>]), slope<span class="op">=</span>lm[<span class="dv">1</span>], label<span class="op">=</span><span class="st">'Regression line</span><span class="ch">\n</span><span class="st">y = '</span> <span class="op">+</span> <span class="st">"</span><span class="sc">{beta_0:.3f}</span><span class="st">"</span>.<span class="bu">format</span>(beta_0<span class="op">=</span>lm[<span class="dv">0</span>]) <span class="op">+</span> <span class="st">' + '</span> <span class="op">+</span> <span class="st">"</span><span class="sc">{beta_1:.3f}</span><span class="st"> "</span>.<span class="bu">format</span>(beta_1<span class="op">=</span>lm[<span class="dv">1</span>]) <span class="op">+</span> <span class="st">'x'</span>)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>plt.annotate(<span class="st">"$R^2$ = </span><span class="sc">{:.2f}</span><span class="st">"</span>.<span class="bu">format</span>(np.corrcoef(x, y)[<span class="dv">0</span>, <span class="dv">1</span>] <span class="op">**</span> <span class="dv">2</span>), (<span class="bu">max</span>(x) <span class="op">*</span> <span class="fl">0.9</span>, <span class="dv">1</span>))</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw 95% confidence interval</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a><span class="co">## poly.polyval(hooke['distance'], [lm[0]])</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>beta1_lower_boundary <span class="op">=</span> lm[<span class="dv">1</span>] <span class="op">-</span> (t_value <span class="op">*</span> standard_error_beta_1)</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>beta1_upper_boundary <span class="op">=</span> lm[<span class="dv">1</span>] <span class="op">+</span> (t_value <span class="op">*</span> standard_error_beta_1)</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>y_lower_boundary <span class="op">=</span> poly.polyval(hooke[<span class="st">'distance'</span>], [lm[<span class="dv">0</span>], beta1_lower_boundary])</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>y_upper_boundary <span class="op">=</span> poly.polyval(hooke[<span class="st">'distance'</span>], [lm[<span class="dv">0</span>], beta1_upper_boundary])</span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>plt.fill_between(x<span class="op">=</span>x, y1<span class="op">=</span>y_lower_boundary, y2<span class="op">=</span>y_upper_boundary, alpha<span class="op">=</span><span class="fl">0.3</span>, label<span class="op">=</span><span class="st">'95</span><span class="sc">% c</span><span class="st">onfidence interval $</span><span class="ch">\\</span><span class="st">beta_1$'</span>)</span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a>plt.title(label<span class="op">=</span><span class="st">'Measured data and estimated linear function within 95</span><span class="sc">% i</span><span class="st">nterval'</span>)</span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Measured change in displacement [m]'</span>)</span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Applied force [N]'</span>)</span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lineare-parameterschätzung_files/figure-html/cell-29-output-1.png" alt="Experimental spring data (change in displacement vs. applied force) with fitted regression line and 95% confidence interval for the slope." width="578" height="451" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-scipy-module" class="level3">
<h3 class="anchored" data-anchor-id="the-scipy-module">The SciPy Module</h3>
<p>The function <code>scipy.stats.linregress(x, y)</code> returns multiple values in a single function call:</p>
<ul>
<li>Slope of the regression line,</li>
<li>y-intercept of the regression line,</li>
<li>Bravais-Pearson correlation coefficient r,</li>
<li>p-value for the null hypothesis that the slope of the regression line is zero,</li>
<li>Standard error of the slope, and</li>
<li>Standard error of the y-intercept.</li>
</ul>
<p>The standard error of the y-intercept is only available if the return values are stored in an object. The values can then be accessed as attributes.</p>
<div id="9f55f3b1" class="cell" data-execution_count="29">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assigning multiple objects</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>slope, intercept, rvalue, pvalue, slope_stderr <span class="op">=</span> scipy.stats.linregress(x, y)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"y = </span><span class="sc">{</span>intercept<span class="sc">:.4f}</span><span class="ss"> + </span><span class="sc">{</span>slope<span class="sc">:.4f}</span><span class="ss"> * x</span><span class="ch">\n</span><span class="ss">"</span>,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"r = </span><span class="sc">{</span>rvalue<span class="sc">:.4f}</span><span class="ss"> R2 = </span><span class="sc">{</span>rvalue <span class="op">**</span> <span class="dv">2</span><span class="sc">:.4f}</span><span class="ss"> p = </span><span class="sc">{</span>pvalue<span class="sc">:.4f}</span><span class="ch">\n</span><span class="ss">"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"Standard error of slope: </span><span class="sc">{</span>slope_stderr<span class="sc">:.4f}</span><span class="ss">"</span>, sep<span class="op">=</span><span class="st">''</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Assigning a single object</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>lm <span class="op">=</span> scipy.stats.linregress(x, y)</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span>, lm, sep<span class="op">=</span><span class="st">''</span>)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"y-intercept: </span><span class="sc">{</span>lm<span class="sc">.</span>intercept<span class="sc">:.4f}</span><span class="ch">\n</span><span class="ss">Standard error of y-intercept: </span><span class="sc">{</span>lm<span class="sc">.</span>intercept_stderr<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>y = 0.0575 + 33.0190 * x
r = 0.9928 R2 = 0.9856 p = 0.0000
Standard error of slope: 0.3784

LinregressResult(slope=np.float64(33.018995509180165), intercept=np.float64(0.057531589079702794), rvalue=np.float64(0.9927907555799096), pvalue=np.float64(4.1152117198381846e-104), stderr=np.float64(0.3783732001932878), intercept_stderr=np.float64(0.050670797267693676))
y-intercept: 0.0575
Standard error of y-intercept: 0.0507</code></pre>
</div>
</div>
<p>This allows the confidence interval to be calculated using the corresponding t-value.</p>
<div id="660bccaa" class="cell" data-execution_count="30">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(x)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>slope <span class="op">-</span> scipy<span class="sc">.</span>stats<span class="sc">.</span>t<span class="sc">.</span>ppf(q <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> alpha <span class="op">/</span> <span class="dv">2</span>, df <span class="op">=</span> n <span class="op">-</span> <span class="dv">2</span>) <span class="op">*</span> slope_stderr<span class="sc">:.3f}</span><span class="ss"> ≤ </span><span class="sc">{</span>slope<span class="sc">:.3f}</span><span class="ss"> ≤ </span><span class="sc">{</span>slope <span class="op">+</span> scipy<span class="sc">.</span>stats<span class="sc">.</span>t<span class="sc">.</span>ppf(q <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> alpha <span class="op">/</span> <span class="dv">2</span>, df <span class="op">=</span> n <span class="op">-</span> <span class="dv">2</span>) <span class="op">*</span> slope_stderr<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>32.269 ≤ 33.019 ≤ 33.769</code></pre>
</div>
</div>
</section>
<section id="spring-constant-result" class="level3">
<h3 class="anchored" data-anchor-id="spring-constant-result">Spring Constant Result</h3>
<p>The spring constant of the experimental setup lies, with 95 percent confidence, within the interval between 32.27 and 33.77. The point estimate for the spring constant is 33.02.</p>
<p><strong>The task could be to calculate the 99-percent confidence interval.</strong><br>
–&gt; In that case, only one number needs to be changed.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Baitsch-2019" class="csl-entry" role="listitem">
Baitsch, Matthias. 2019. <em>Vorlesungsskript Mathematik b (Master) Stochastik</em>. Hochschule Bochum.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../skript/normalverteilung.html" class="pagination-link" aria-label="The Normal Distribution">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Normal Distribution</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../skript/fehlerrechnung.html" class="pagination-link" aria-label="Error Calculation">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Error Calculation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>